inputs:
  node-version:
    description: 'node version'
    required: false
    default: ''
  node-version-file:
    description: 'node version file'
    required: false
    default: '.node-version'

name: 'Setup Node and run npm ci'
description: 'setup node env'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ inputs.node-version }}'
        node-version-file: '${{ inputs.node-version-file }}'

    - run: |
        corepack enable
        corepack prepare --activate
        pnpm --version
      shell: bash
      name: install pnpm

    - name: Get nodejs version
      shell: bash
      id: nodejs-version
      run: echo "version=$(node -e 'console.log(process.version)')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ~/.local/share/pnpm/store/
        key: ${{ runner.os }}-node${{ steps.nodejs-version.outputs.version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node${{ steps.nodejs-version.outputs.version }}-

    - name: Install Dependencies
      run: pnpm i --frozen-lockfile
      shell: bash
