name: next-version

on:
  push:
    branches: [master]

concurrency:
  group: next-version
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  github:
    if: ${{ github.repository_owner == 'bangumi' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - run: echo "NEW_TAG=$(git cliff --bumped-version)" >> $GITHUB_ENV
      - run: echo "NEW_VERSION=${NEW_TAG#v}" >> $GITHUB_ENV

      - run: git cliff --unreleased -o changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: python ./.github/scripts/avoid-changelog-ref.py changelog.md

      - run: |
          jq ".version = \"${NEW_VERSION}\"" package.json > tmp
          rm package.json
          mv tmp package.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          title: 'bump: ${{ env.NEW_VERSION }}'
          branch: 'ci/release-next-version'
          body-path: changelog.md
          assignees: '@trim21'
          commit-message: 'bump: ${{ env.NEW_VERSION }}'
